# Generated by Django 4.1.1 on 2022-10-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('asignacion', models.CharField(max_length=50)),
                ('invitados', models.IntegerField()),
                ('fecha_pago', models.DateField()),
            ],
        ),
    ]
