# Generated by Django 4.1.1 on 2022-10-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ver_familia', '0002_subfamilia_delete_familiar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfamilia',
            name='fecha_pago',
            field=models.DateField(null=True),
        ),
    ]
